TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
DB += ai_hist.db
DB += ai_hist_RFChan.db
DB += ai_hist_calcPhase.db
DB += fsControls.template
DB += vitaraAuto.template
DB += vitaraFreqSearch.template
DB += vitaraPID.template
DB += vitaraRFChan.template
DB += subR_laserLocker.db
DB += subRHL_laserLocker.db
DB += HL_laserLocker.db
DB += alias.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

